/**
 * Focused production-dispatcher proof for author-confirmed news №14.
 *
 * The test starts from the compiled immutable game bundle, enters only the
 * upstream news-card condition directly, and then executes both card
 * activation and maintenance completion through the ordinary dispatcher.
 * Thus the assertions cover the real typed plans, atomic transaction boundary,
 * durable modifier, team thresholds and public journal rather than a duplicate
 * JavaScript implementation of the rule.
 */

import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import authoringCompiler from "../../../scripts/manifest-tools/authoring-compiler.cjs";
import { createImmutableBundleContent } from "../../../services/runtime-api/src/modules/content/immutableBundle.ts";
import { validateGameManifest } from "../../../services/runtime-api/src/modules/content/manifestValidation.ts";
import { dispatchRuntimeAction } from "../../../services/runtime-api/src/modules/runtime/actionDispatcher.ts";
import { InMemorySessionStore } from "../../../services/runtime-api/src/modules/session/inMemorySessionStore.ts";
import {
  authoringPath,
  buildLifecycleAuthoring
} from "./build-card-lifecycle.mjs";
import { buildOperatingTurnAuthoring } from "./build-operating-turn.mjs";
import { buildSessionSetupAuthoring } from "./build-session-setup.mjs";

const toolsRoot = path.dirname(fileURLToPath(import.meta.url));
const gameRoot = path.resolve(toolsRoot, "..");
const repoRoot = path.resolve(gameRoot, "..", "..");
const intakePath = path.join(
  gameRoot,
  "authoring",
  "fixtures",
  "cargo-news.intake.json"
);
const networkPath = path.join(
  gameRoot,
  "annotations",
  "initial-network.review.json"
);
const credentialSha256 = "4".repeat(64);
const admissionController = {
  async assertNewCommandAdmitted() {}
};
let commandSequence = 0;
let manifestPromise;
let authoringPromise;

const readJson = async (absolutePath) =>
  JSON.parse(await readFile(absolutePath, "utf8"));

const nextCommandId = () => {
  const bytes = Buffer.alloc(16);
  bytes.writeUInt32BE(++commandSequence, 12);
  return `cli_${bytes.toString("base64url")}`;
};

/**
 * Apply the complete news №14 generator chain without requiring the shared
 * checked-in authoring file to have been regenerated by the orchestrator yet.
 */
const buildNews14Authoring = async () => {
  authoringPromise ??= (async () => {
    const [source, intake, network] = await Promise.all([
      readJson(authoringPath),
      readJson(intakePath),
      readJson(networkPath)
    ]);
    return buildOperatingTurnAuthoring(
      buildLifecycleAuthoring(
        buildSessionSetupAuthoring(source, network),
        intake
      )
    );
  })();
  return structuredClone(await authoringPromise);
};

/** Compile once in memory without writing a production manifest. */
const loadManifest = async () => {
  manifestPromise ??= (async () => {
    const authoring = await buildNews14Authoring();
    const output = authoringCompiler.compileAuthoringText(
      {
        kind: "game",
        sourceFile: authoringPath,
        outputFile: path.join(repoRoot, ".tmp", "cmt-news-14.manifest.json"),
        sourceMapFile: path.join(
          repoRoot,
          ".tmp",
          "cmt-news-14.manifest.source-map.json"
        )
      },
      `${JSON.stringify(authoring, null, 2)}\n`
    );
    return validateGameManifest(output.manifest);
  })();
  return manifestPromise;
};

const makeTeam = ({ id, type, coins }) => [
  id,
  {
    objectType: "game.team",
    facets: { placementStatus: "placed" },
    attributes: {
      label: id,
      type,
      colorId: id,
      coins,
      constructionPledge: 0,
      placementOrderKey: 0,
      progressiveTaxLocomotiveCount: 0,
      progressiveTaxWagonCount: 0
    }
  }
];

const makeLocomotive = ({ id, ownerTeamId, turnNumber }) => [
  id,
  {
    objectType: "transport.locomotive",
    facets: { availability: "active" },
    attributes: {
      networkId: "main",
      nodeId: "terminal-1",
      ownerTeamId,
      actionPoints: 5,
      turnOrderCount: 0,
      movementResolvedTurn: 0,
      lastMovedTurn: 0,
      maintenancePaidTurn: turnNumber
    }
  }
];

const makeWagon = ({ id, ownerTeamId, turnNumber }) => [
  id,
  {
    objectType: "transport.wagon",
    facets: { availability: "active" },
    attributes: {
      networkId: "main",
      nodeId: "terminal-1",
      ownerTeamId,
      attachedVehicleId: null,
      cargoId: null,
      maintenancePaidTurn: turnNumber,
      cargoOfferEligibleTurn: 0,
      cargoOfferResolvedTurn: 0,
      cargoPriorityActiveCount: 0
    }
  }
];

/** Repeat a factory with stable identifiers so selection order is explicit. */
const repeatEntities = (count, prefix, ownerTeamId, turnNumber, factory) =>
  Object.fromEntries(
    Array.from({ length: count }, (_, index) =>
      factory({
        id: `${prefix}-${String(index + 1).padStart(2, "0")}`,
        ownerTeamId,
        turnNumber
      })
    )
  );

/**
 * Build the exact upstream state immediately before news №14 is applied.
 *
 * Vehicle maintenance is already settled for this turn because this test
 * targets the additional progressive tax at phase completion, not the
 * separately covered one-coin per-unit maintenance actions.
 */
const createNews14State = (manifest, {
  turnNumber = 2,
  teams,
  locomotives = {},
  wagons = {}
}) => {
  const state = structuredClone(manifest.state);
  state.public.session.fixtureId = "normal-start-policy";
  state.public.session.status = "running";
  state.public.session.phase = "news";
  state.public.session.turnNumber = turnNumber;
  state.public.cards.initialized = true;
  state.public.news.currentCardId = "news-14";
  state.public.news.status = "drawn";
  state.public.objects.newsCards["news-14"].facets.availability = "current";
  state.public.objects.teams = Object.fromEntries(teams);
  state.public.objects.locomotives = locomotives;
  state.public.objects.wagons = wagons;
  state.public.log = [];
  return state;
};

const createSession = async (manifest, initialState) => {
  const store = new InMemorySessionStore();
  const created = await store.createSession({
    gameId: manifest.meta.id,
    sessionRole: "facilitator",
    initialState,
    immutableBundle: createImmutableBundleContent(manifest.meta.id, manifest),
    principal: {
      principalId: "news-14-test-facilitator",
      kind: "local-controller",
      role: "facilitator",
      actorScope: { kind: "all-session-actors" },
      credentialSha256
    }
  });
  return { store, sessionId: created.session.sessionId };
};

const dispatch = async ({ store, sessionId, actionId, params = {} }) => {
  const current = await store.getSession(sessionId);
  return dispatchRuntimeAction({
    sessionStore: store,
    credentialSha256,
    admissionController,
    input: {
      sessionId,
      actionId,
      commandId: nextCommandId(),
      expectedStateVersion: current.version.stateVersion,
      params
    }
  });
};

const updateScenario = async ({ store, sessionId }, mutate) => {
  const current = await store.getSession(sessionId);
  const updated = structuredClone(current);
  mutate(updated.state);
  updated.version.stateVersion += 1;
  updated.updatedAt = new Date();
  await store.updateSession(updated, {
    expectedStateVersion: current.version.stateVersion
  });
};

const assertRejectedWithoutMutation = async (session, actionId) => {
  const before = await session.store.getSession(session.sessionId);
  let rejected = false;
  try {
    const outcome = await dispatch({ ...session, actionId });
    rejected = outcome.result.ok === false && outcome.receipt.status === "rejected";
  } catch {
    rejected = true;
  }
  assert.equal(rejected, true, `${actionId} must be rejected`);
  const after = await session.store.getSession(session.sessionId);
  assert.equal(after.version.stateVersion, before.version.stateVersion);
  assert.deepEqual(after.state, before.state);
};

test("generators preserve the persistent news №14 contract idempotently", async () => {
  const [source, intake, network] = await Promise.all([
    buildNews14Authoring(),
    readJson(intakePath),
    readJson(networkPath)
  ]);
  const rebuilt = buildOperatingTurnAuthoring(
    buildLifecycleAuthoring(
      buildSessionSetupAuthoring(source, network),
      intake
    )
  );
  assert.deepEqual(
    rebuilt,
    source
  );
  assert.equal(
    rebuilt.root.state.public.ruleModifiers.progressiveAssetTaxActive,
    false
  );
  assert.ok(
    rebuilt.root.logic.actions.some((action) => action.id === "news.effect.apply.14")
  );
  assert.deepEqual(
    rebuilt.root.config.runtimeBlockers.filter((item) => /news effects/u.test(item)),
    ["remaining executable news effects 19, 28 and 29"]
  );
});

test("news №14 persists and taxes both team types above their exact thresholds every turn", async () => {
  const manifest = await loadManifest();
  const turnNumber = 2;
  const teams = [
    makeTeam({ id: "guild-taxed", type: "locomotive_guild", coins: 10 }),
    makeTeam({ id: "guild-threshold", type: "locomotive_guild", coins: 10 }),
    makeTeam({ id: "logistics-taxed", type: "logistics_company", coins: 10 }),
    makeTeam({ id: "logistics-threshold", type: "logistics_company", coins: 10 })
  ];
  const locomotives = {
    ...repeatEntities(
      4,
      "guild-taxed-locomotive",
      "guild-taxed",
      turnNumber,
      makeLocomotive
    ),
    ...repeatEntities(
      3,
      "guild-threshold-locomotive",
      "guild-threshold",
      turnNumber,
      makeLocomotive
    )
  };
  const wagons = {
    ...repeatEntities(
      7,
      "logistics-taxed-wagon",
      "logistics-taxed",
      turnNumber,
      makeWagon
    ),
    ...repeatEntities(
      5,
      "logistics-threshold-wagon",
      "logistics-threshold",
      turnNumber,
      makeWagon
    )
  };
  const session = await createSession(
    manifest,
    createNews14State(manifest, { turnNumber, teams, locomotives, wagons })
  );

  const applied = await dispatch({
    ...session,
    actionId: "news.effect.apply.14"
  });
  assert.equal(applied.result.ok, true);
  const afterApply = await session.store.getSession(session.sessionId);
  assert.equal(
    afterApply.state.public.ruleModifiers.progressiveAssetTaxActive,
    true
  );
  assert.equal(afterApply.state.public.session.phase, "maintenance");
  assert.deepEqual(afterApply.state.public.log.at(-1)?.data, {
    newsId: "news-14",
    active: true,
    turnNumber
  });

  const finished = await dispatch({
    ...session,
    actionId: "maintenance.phase.finish"
  });
  assert.equal(finished.result.ok, true);
  const afterFirstTax = await session.store.getSession(session.sessionId);
  const firstTeams = afterFirstTax.state.public.objects.teams;
  assert.equal(firstTeams["guild-taxed"].attributes.coins, 9);
  assert.equal(firstTeams["guild-threshold"].attributes.coins, 10);
  assert.equal(firstTeams["logistics-taxed"].attributes.coins, 8);
  assert.equal(firstTeams["logistics-threshold"].attributes.coins, 10);
  assert.equal(firstTeams["guild-taxed"].attributes.progressiveTaxLocomotiveCount, 4);
  assert.equal(firstTeams["logistics-taxed"].attributes.progressiveTaxWagonCount, 7);
  assert.equal(afterFirstTax.state.public.session.phase, "market");

  const firstEvents = afterFirstTax.state.public.log
    .filter((event) => event.eventType === "maintenance.progressive-asset-tax.paid")
    .map((event) => event.data);
  assert.deepEqual(firstEvents, [
    {
      kind: "progressive-asset-tax",
      newsId: "news-14",
      teamId: "guild-taxed",
      teamType: "locomotive_guild",
      assetKind: "locomotive",
      ownedUnitCount: 4,
      threshold: 3,
      taxableUnitCount: 1,
      chargedAmount: 1,
      balanceAfter: 9,
      turnNumber: 2
    },
    {
      kind: "progressive-asset-tax",
      newsId: "news-14",
      teamId: "logistics-taxed",
      teamType: "logistics_company",
      assetKind: "wagon",
      ownedUnitCount: 7,
      threshold: 5,
      taxableUnitCount: 2,
      chargedAmount: 2,
      balanceAfter: 8,
      turnNumber: 2
    }
  ]);

  await updateScenario(session, (state) => {
    state.public.session.phase = "maintenance";
    state.public.session.turnNumber = 3;
    for (const locomotive of Object.values(state.public.objects.locomotives)) {
      locomotive.attributes.maintenancePaidTurn = 3;
    }
    for (const wagon of Object.values(state.public.objects.wagons)) {
      wagon.attributes.maintenancePaidTurn = 3;
    }
  });
  const repeated = await dispatch({
    ...session,
    actionId: "maintenance.phase.finish"
  });
  assert.equal(repeated.result.ok, true);
  const afterSecondTax = await session.store.getSession(session.sessionId);
  assert.equal(
    afterSecondTax.state.public.ruleModifiers.progressiveAssetTaxActive,
    true
  );
  assert.equal(
    afterSecondTax.state.public.objects.teams["guild-taxed"].attributes.coins,
    8
  );
  assert.equal(
    afterSecondTax.state.public.objects.teams["logistics-taxed"].attributes.coins,
    6
  );
  assert.deepEqual(
    afterSecondTax.state.public.log
      .filter(
        (event) =>
          event.eventType === "maintenance.progressive-asset-tax.paid"
          && event.data.turnNumber === 3
      )
      .map((event) => event.data.chargedAmount),
    [1, 2]
  );
});

test("insufficient progressive tax rolls back every team debit, counter and journal event", async () => {
  const manifest = await loadManifest();
  const turnNumber = 2;
  const teams = [
    makeTeam({ id: "a-guild", type: "locomotive_guild", coins: 1 }),
    makeTeam({ id: "b-logistics", type: "logistics_company", coins: 1 })
  ];
  const locomotives = repeatEntities(
    4,
    "a-locomotive",
    "a-guild",
    turnNumber,
    makeLocomotive
  );
  const wagons = repeatEntities(
    7,
    "b-wagon",
    "b-logistics",
    turnNumber,
    makeWagon
  );
  const session = await createSession(
    manifest,
    createNews14State(manifest, { turnNumber, teams, locomotives, wagons })
  );
  assert.equal(
    (await dispatch({ ...session, actionId: "news.effect.apply.14" })).result.ok,
    true
  );

  await assertRejectedWithoutMutation(session, "maintenance.phase.finish");
  const after = await session.store.getSession(session.sessionId);
  assert.equal(after.state.public.session.phase, "maintenance");
  assert.equal(after.state.public.objects.teams["a-guild"].attributes.coins, 1);
  assert.equal(after.state.public.objects.teams["b-logistics"].attributes.coins, 1);
  assert.equal(
    after.state.public.objects.teams["a-guild"].attributes
      .progressiveTaxLocomotiveCount,
    0
  );
  assert.equal(
    after.state.public.objects.teams["b-logistics"].attributes
      .progressiveTaxWagonCount,
    0
  );
  assert.equal(
    after.state.public.log.filter(
      (event) => event.eventType === "maintenance.progressive-asset-tax.paid"
    ).length,
    0
  );
});
